name: Protips
main: net.thedarktide.squallseed31.protips.Protips
version: 0.2.0.10
author: SquallSeeD31
commands:
  protips:
    description: Alias for /protip
    usage: /<command> help for usage details
  protip:
    description: Command-line access to Protips functions.
    usage: /<command> help for usage details